# Generated by Django 3.2 on 2021-05-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_signature',
        ),
    ]
