# Generated by Django 3.2 on 2021-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210512_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amt_str',
            field=models.CharField(default='0.4k', max_length=255),
        ),
    ]
