# Generated by Django 3.2 on 2021-05-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_wallet_amt_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='ID',
            field=models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amt_str',
            field=models.CharField(default='0.0k', max_length=255),
        ),
    ]
