# Generated by Django 3.2 on 2021-04-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='business', max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.IntegerField(blank=True, choices=[(0, 'England'), (1, 'Scotland'), (2, 'Wales'), (4, 'Northern Irealand')], default=0, null=True)),
                ('address', models.CharField(default=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
