# Generated by Django 3.2 on 2021-05-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20210503_1521'),
        ('users', '0008_businessusp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessusp',
            name='business',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessUSP',
        ),
    ]
