# Generated by Django 3.2 on 2021-04-26 19:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_business_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reach', models.CharField(blank=True, default='0.0k', max_length=255, null=True)),
                ('click', models.CharField(blank=True, default='0.0k', max_length=255, null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMarketingCampaign',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_mail_send', models.IntegerField(default=0)),
                ('reach', models.CharField(blank=True, default='0.0k', max_length=255, null=True)),
                ('click', models.CharField(blank=True, default='0.0k', max_length=255, null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=0.0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.business')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPlatform',
            fields=[
                ('_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='marketingplatform')),
            ],
        ),
        migrations.CreateModel(
            name='UsersforEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_status', models.IntegerField(choices=[(0, 'Not Sended'), (1, 'Sended')], default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.customer')),
                ('email_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.emailmarketingcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+44', max_length=128, region=None, unique=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='ctype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.campaigntype'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.marketingplatform'),
        ),
    ]
