# Generated by Django 3.2 on 2021-04-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_business_address'),
        ('marketing', '0002_auto_20210427_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='business',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_root',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marketing.campaignroot'),
        ),
        migrations.AddField(
            model_name='campaignroot',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.business'),
        ),
        migrations.DeleteModel(
            name='GroupOfCampaign',
        ),
    ]
