# Generated by Django 3.2 on 2021-04-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20210427_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignroot',
            name='status',
            field=models.IntegerField(choices=[(1, 'Running'), (2, 'Stoped'), (3, 'Terminated')], default=1),
        ),
    ]
