# Generated by Django 3.2 on 2021-04-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_campaignroot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingplatform',
            name='color',
            field=models.CharField(default='rgba(0,0,0,1)', max_length=255),
        ),
    ]
