# Generated by Django 3.2 on 2021-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_getintouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouch',
            name='ID',
            field=models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
