# Generated by Django 3.2 on 2021-05-21 09:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_alter_getintouch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+44', max_length=128, region=None),
        ),
    ]
