# Generated by Django 3.2 on 2021-05-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessUSP',
            new_name='USP',
        ),
    ]
