# Generated by Django 3.2 on 2021-05-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_businessusp_usp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
