# Generated by Django 3.2 on 2021-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_zipcode_business_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
