# Generated by Django 3.2 on 2021-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='usp',
            name='id',
        ),
        migrations.AddField(
            model_name='goals',
            name='ID',
            field=models.CharField(auto_created=True, default=1, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usp',
            name='ID',
            field=models.CharField(auto_created=True, default=1, max_length=255, primary_key=True, serialize=False),
        ),
    ]
