# Generated by Django 3.2 on 2021-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20210512_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='_id',
            new_name='ID',
        ),
    ]
